#!/usr/bin/env python3
"""gen_primitive_objects.py — procedural object-set generator for the
cross-object-group generalization study.

Emits parametric primitive URDFs (native box / cylinder / sphere geometry, so
IsaacGym uses analytic collision — no meshes or VHACD) into the directory layout
that leap_hand_rot.py already globs:

    <assets>/<category>/<subset>/obj_<i>.urdf

where category in {cuboid, cylinder, sphere}. A `subset` is one "object family":
LeapHandRot samples an object per env from the family, and one shared grasp cache
is generated per family (see tools/gen_grasp_caches.py).

Taxonomy (2 levels):
  * category  = strategy-defining shape class (roller / box-pivot / cylinder).
  * instance  = continuous variation within a class (aspect ratio, size).
We emit a `train` subset (in-distribution) and a `heldout` subset (tests
within-category generalization) per category. Categories themselves are the
cross-category (hard) generalization axis.

Inertia is computed for a uniform-density solid so shapes are physically
distinct (a flat slab and a rod differ in their inertia tensor — part of what
makes categories behave differently). Sizes are chosen near the known-graspable
cube (0.075 m box) so the LEAP hand can form an initial grip.

Usage (from src/LEAP_Hand_Sim/leapsim):
    uv run python tools/gen_primitive_objects.py            # writes ../assets/...
    uv run python tools/gen_primitive_objects.py --dry-run  # list, write nothing
"""
from __future__ import annotations

import argparse
from pathlib import Path

# Uniform density [kg/m^3]. ~200 puts a ~0.07 m cube near 0.07 kg, in the same
# ballpark as the hand-tuned existing assets (cube.urdf mass 0.05).
DEFAULT_DENSITY = 200.0

# ---------------------------------------------------------------------------- #
# Taxonomy. Each entry is (category, subset, [instances]). Instance params:
#   cuboid  : ('box',  (sx, sy, sz))      full extents [m]
#   cylinder: ('cyl',  (radius, length))  length along z [m]
#   sphere  : ('sph',  (radius,))         [m]
# ---------------------------------------------------------------------------- #
TAXONOMY = {
    ("cuboid", "train"): [
        ("box", (0.070, 0.070, 0.070)),   # near-cube
        ("box", (0.085, 0.075, 0.045)),   # slab
        ("box", (0.095, 0.050, 0.050)),   # bar
        ("box", (0.055, 0.055, 0.090)),   # tall
        ("box", (0.080, 0.060, 0.055)),   # block
        ("box", (0.090, 0.070, 0.035)),   # flat
    ],
    ("cuboid", "heldout"): [
        ("box", (0.075, 0.060, 0.065)),
        ("box", (0.100, 0.045, 0.045)),   # long bar
        ("box", (0.065, 0.065, 0.080)),
    ],
    ("cylinder", "train"): [
        ("cyl", (0.032, 0.080)),          # can
        ("cyl", (0.050, 0.030)),          # disk / puck
        ("cyl", (0.022, 0.100)),          # rod
        ("cyl", (0.042, 0.050)),          # squat
    ],
    ("cylinder", "heldout"): [
        ("cyl", (0.028, 0.090)),
        ("cyl", (0.045, 0.040)),
    ],
    ("sphere", "train"): [
        ("sph", (0.032,)),
        ("sph", (0.040,)),
    ],
    ("sphere", "heldout"): [
        ("sph", (0.045,)),
    ],
}


def _inertia(kind: str, dims, mass: float):
    """Principal moments (ixx, iyy, izz) of a uniform-density solid about its COM."""
    if kind == "box":
        a, b, c = dims                       # full extents
        k = mass / 12.0
        return k * (b * b + c * c), k * (a * a + c * c), k * (a * a + b * b)
    if kind == "cyl":
        r, h = dims                          # axis along z
        ixx = mass * (3.0 * r * r + h * h) / 12.0
        return ixx, ixx, 0.5 * mass * r * r
    if kind == "sph":
        r = dims[0]
        i = 0.4 * mass * r * r
        return i, i, i
    raise ValueError(kind)


def _volume(kind: str, dims) -> float:
    import math
    if kind == "box":
        return dims[0] * dims[1] * dims[2]
    if kind == "cyl":
        return math.pi * dims[0] ** 2 * dims[1]
    if kind == "sph":
        return 4.0 / 3.0 * math.pi * dims[0] ** 3
    raise ValueError(kind)


def _geometry_xml(kind: str, dims) -> str:
    if kind == "box":
        return f'<box size="{dims[0]:.6f} {dims[1]:.6f} {dims[2]:.6f}"/>'
    if kind == "cyl":
        return f'<cylinder radius="{dims[0]:.6f}" length="{dims[1]:.6f}"/>'
    if kind == "sph":
        return f'<sphere radius="{dims[0]:.6f}"/>'
    raise ValueError(kind)


def _urdf(kind: str, dims, density: float) -> str:
    mass = density * _volume(kind, dims)
    ixx, iyy, izz = _inertia(kind, dims, mass)
    geom = _geometry_xml(kind, dims)
    return f"""<?xml version="1.0"?>
<!-- Auto-generated by tools/gen_primitive_objects.py. kind={kind} dims={dims} -->
<robot name="object">
  <link name="object">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        {geom}
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        {geom}
      </geometry>
    </collision>
    <inertial>
      <mass value="{mass:.6f}"/>
      <inertia ixx="{ixx:.8f}" ixy="0.0" ixz="0.0" iyy="{iyy:.8f}" iyz="0.0" izz="{izz:.8f}"/>
    </inertial>
  </link>
</robot>
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--assets-dir", default=None,
                    help="Assets root (default: <this file>/../../assets, i.e. src/LEAP_Hand_Sim/assets)")
    ap.add_argument("--density", type=float, default=DEFAULT_DENSITY, help="Uniform density [kg/m^3]")
    ap.add_argument("--dry-run", action="store_true", help="Print what would be written, write nothing")
    args = ap.parse_args()

    # tools/ lives in .../leapsim/tools; assets are at .../src/LEAP_Hand_Sim/assets
    assets = Path(args.assets_dir) if args.assets_dir else (Path(__file__).resolve().parents[2] / "assets")

    n = 0
    for (category, subset), instances in TAXONOMY.items():
        out_dir = assets / category / subset
        for i, (kind, dims) in enumerate(instances):
            path = out_dir / f"obj_{i}.urdf"
            mass = args.density * _volume(kind, dims)
            print(f"{'[dry] ' if args.dry_run else ''}{path}  ({kind} {dims}, m={mass:.3f} kg)")
            if not args.dry_run:
                out_dir.mkdir(parents=True, exist_ok=True)
                path.write_text(_urdf(kind, dims, args.density))
            n += 1

    print(f"\n{'Would write' if args.dry_run else 'Wrote'} {n} URDFs across "
          f"{len(TAXONOMY)} families under {assets}")
    if not args.dry_run:
        print("Object types for training/grasp-gen, e.g.: "
              "task.env.object.type=cuboid_train | cylinder_train | sphere_train")


if __name__ == "__main__":
    main()
